<a href="https://colab.research.google.com/github/Alexander-Resch/Colab_Notebooks/blob/main/Triangles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
def add_Noise(X=[0,0],sigma=1,mu=0,sigma_alpha=0):

  X[0] = X[0]+sigma*np.random.randn()+mu
  X[1] = X[1]+sigma*np.random.randn()+mu
  rotation = 0.05*np.random.randn()

  return X, rotation

def rotate_triangle(Coordinates,angle_in_degrees,center_of_rotation=(0,0)):

  rotation = angle_in_degrees*np.pi/180 #convert to radian
  M = np.array([[np.cos(rotation),-np.sin(rotation)],[np.sin(rotation),np.cos(rotation)]])



def make_triangle(T=[0,500], rotation = 0,B=[0,0],W=[1000,0]):
  dWB = 1000
  dTB = 500
  dTW = np.sqrt((500**2)+(1000**2))
  T_old = np.array([0,500])
  
  # T is passed as a noisy point
  T = np.array(T)
  
  #calculate new B and W values based on noisy T with rotation Matrix
  rotation = rotation*np.pi/180 #convert to radian
  M = np.array([[np.cos(rotation),-np.sin(rotation)],[np.sin(rotation),np.cos(rotation)]])
  #print(M)
  
  B = np.array(B) + dTB

  W = np.array(W)
  

  Position_T = T 
  

  return Position_T

make_triangle(rotation=45)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


array([  0, 500])

In [ ]:

q = []
for i in range(1000):
  T = [0,500] #initial position
  T,_ = add_Noise(T)
  q.append(make_triangle(T))

x = [x[0] for x in q]
y = [x[1] for x in q]
f = plt.figure(figsize = (14,12))

ax = f.add_subplot()
ax.set_ylim([-10,600])
ax.set_xlim([-100,1100])
ax.scatter(x,y)

NameError: ignored

In [ ]:
A = np.array([1,1])
B = np.array([2,3])
A+B

array([3, 4])