<a href="https://colab.research.google.com/github/Alexander-Resch/Colab_Notebooks/blob/main/XOR_functional_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import keras.backend as K
from keras.models import Model, Sequential
from keras.layers import Dense, Input 
import numpy as np


In [51]:
#define data
x_train = np.array([[0,0],[0,1],[1,0],[1,1]], dtype=float)
y_train = np.array([[0],[1],[1],[0]], dtype=float)

print(x_train,'\n\n', y_train)

#define XOR-model
input = Input(shape=(2,))
X = Dense(16, activation = 'relu')(input)
X = Dense(32, activation = 'relu')(X)
X = Dense(10, activation = 'relu')(X)
X = Dense(1, activation='sigmoid')(X)
model = Model(inputs=input,outputs=X)
model.compile(loss='mse',optimizer='adam',metrics='mse')
model.summary()
model.fit(x_train,y_train,epochs=1000,verbose=1)
model.predict(x_train).round()

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]] 

 [[0.]
 [1.]
 [1.]
 [0.]]
Model: "model_40"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_43 (InputLayer)        [(None, 2)]               0         
_________________________________________________________________
dense_85 (Dense)             (None, 16)                48        
_________________________________________________________________
dense_86 (Dense)             (None, 32)                544       
_________________________________________________________________
dense_87 (Dense)             (None, 10)                330       
_________________________________________________________________
dense_88 (Dense)             (None, 1)                 11        
Total params: 933
Trainable params: 933
Non-trainable params: 0
_________________________________________________________________
Epoch 1/1000
1/1 [==============================] - 0s 367ms/

array([[0.],
       [1.],
       [1.],
       [0.]], dtype=float32)

In [52]:
model.weights

[<tf.Variable 'dense_85/kernel:0' shape=(2, 16) dtype=float32, numpy=
 array([[ 0.1470668 ,  0.42394254, -0.16195372,  0.7323004 , -0.01735819,
          0.5923244 ,  0.6973741 , -0.41851854, -0.5496874 ,  0.56503934,
         -0.8325937 , -0.25605032, -0.4941816 , -0.35533345,  0.47346205,
         -0.19586569],
        [ 0.5070764 , -0.8591359 , -0.19050518,  0.7636156 ,  0.73166305,
          0.25336686, -0.20997374,  0.35612002, -0.05584294, -0.5479328 ,
          0.4073835 , -0.01694179,  0.6960538 , -0.42047077,  0.17342117,
          0.39820608]], dtype=float32)>,
 <tf.Variable 'dense_85/bias:0' shape=(16,) dtype=float32, numpy=
 array([-1.01054415e-01,  4.35135901e-01,  0.00000000e+00, -1.79203153e-06,
         5.01532108e-02,  2.88654994e-02,  7.18356669e-02,  8.17366913e-02,
         0.00000000e+00,  6.04073629e-02,  4.36878055e-01,  0.00000000e+00,
         5.79563084e-06,  0.00000000e+00, -1.24363407e-01, -3.13985911e-05],
       dtype=float32)>,
 <tf.Variable 'dense_86/ker